services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy_params:/etc/nginx/proxy_params
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - livekit
    networks:
      - mm-net
  
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mm-net
    expose:
      - 8080
  
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    env_file:
      - ../../frontend/.env
    depends_on:
      - backend
      - livekit
    networks:
       - mm-net
      
  redis:
    image: redis:7
    restart: always
    networks:
      - mm-net
    
  livekit:
    image: livekit/livekit-server:latest
    restart: always
    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml:ro
    ports:
      - "50000-50100:50000-50100/udp"
    command: ["--config", "/etc/livekit/livekit.yaml"]
    depends_on:
      - redis
    networks:
      - mm-net
    expose:
      - 7880

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: yakov
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meremeet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meremeet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - mm-net

volumes:
  postgres_data:

networks:
  mm-net:
    driver: bridge